train_ae: True
first_train_ae: True

epochs: 10
batch_size: 16
lr: 0.0005
num_workers: 8
num_gpus: 1
# num_gpus: 1
val_every_epoch: 1
save_every_epoch: 1

use_wandb_tracking: True
wandb_project_name: line_ae
wandb_name: test

condition_on_text: False
use_text_embeds: False
add_room_codes: False

DATA:
    is_single: False
    # train_set_file_path: /studio/datasets/abc/abc_3d_train.pkl
    # test_set_file_path: /studio/datasets/abc/abc_3d_test.pkl
    train_set_file_path: /studio/projects/meshgpt/meshgpt-pytorch/data
    test_set_file_path: /studio/projects/meshgpt/meshgpt-pytorch/data_test


    replication: 10

MODEL:
    # model_name: line_autoencoder
    # use_linear_attn: False
    use_residual_lfq: True

    codebook_size: 16384
    dim_codebook: 192
    attn_encoder_depth: 4
    attn_decoder_depth: 2
    local_attn_window_size: 64
    encoder_dims_through_depth: [
      64, 128, 256, 256, 576
    ]
    decoder_dims_through_depth: [
      128, 128, 128, 128,
      192, 192, 192, 192,
      256, 256, 256, 256, 256, 256,
      384, 384, 384
    ]
    ae_checkpoint_folder: checkpoints/checkpoints_ae
    ae_ckpt_path: checkpoints/checkpoints_ae/mesh-autoencoder.ckpt.2.pt

